### PR TITLE
Added Type definitions for Typescript compatibility

### PR DESCRIPTION
**Pull request by prajwalkulkarni**
Closes issue: #12 

This PR aims to add type definitions to support Typescript projects using this package.
To avoid external dependencies in the type definition file (`index.d.ts`), I've copied over some types required in the package from `react-beautiful-dnd`, 
e,g: `interface DraggableStateSnapshot` which is the type for the prop `snapshot`.

### CODE REVIEW

**Comment by rokborf** [comment]
Thanks for your PR @prajwalkulkarni 
Please check https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

1. Looks like you need to pick one of the options, not both of them:
```
1. bundling with your npm package
2. publishing to the [@types organization](https://www.npmjs.com/~types) on npm.`
```

2. I don't think copying dependencies type is an optimal solution:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#packaging-dependent-declarations

**Comment by rokborf** [comment]
Thanks, I've left one small comment there.

**Comment by prajwalkulkarni** [comment]
Hello @rokborf, I'm unable to find your comment in the conversation section. Could you please point me to it or let me know if there are any changes to be made? And, the PR is approved, shall I proceed to merge it?

**Comment by rokborf** [comment]
> There is also sigmoidFunction in the props
> By default it's const sigmoid = x => x / (1 + Math.abs(x));

**Comment by prajwalkulkarni** [comment]
Ah, my bad. Didn't notice that. I've added the type definition for the same, kindly confirm if it is good to go or requires any further changes. Thanks!

**Comment by rokborf** [comment]
@prajwalkulkarni yes, looks good to me, thanks

**Comment by rokborf** [comment]
Thanks, @prajwalkulkarni 
@types/natural-drag-animation-rbdnd is available, no need for this PR anymore

**Pull request closed without merging**
